# constants for the geneatic algorithm

# region cdg
# RADIUS = 1
# N_CIRCLES = 4
# POPULATION = 40
# SELECTION_PERCENTAGE = 0.3
# MUTATION_PROBABILITY = 0.3
# CROSSOVER_PROBABILITY = 0.6


# region dlh
RADIUS = 4
N_CIRCLES = 10
POPULATION = 40
SELECTION_PERCENTAGE = 0.3
MUTATION_PROBABILITY = 0.3
CROSSOVER_PROBABILITY = 0.6


# region blr
# RADIUS = 5
# N_CIRCLES = 10
# POPULATION = 40
# SELECTION_PERCENTAGE = 0.3
# MUTATION_PROBABILITY = 0.3
# CROSSOVER_PROBABILITY = 0.6
