# constants for the geneatic algorithm
SEED = None

# region cdg
# RADIUS = 1
# N_CIRCLES = 4
# POPULATION = 40
# SELECTION_PERCENTAGE = 0.35
# MUTATION_PROBABILITY = 0.05
# CROSSOVER_PROBABILITY = 0.6
# MUTATION_RANGE = 0.036
# MUTATION_DISTRIBTION = "uniform"


# region dlh
RADIUS = 4
N_CIRCLES = 10
POPULATION = 40
SELECTION_PERCENTAGE = 0.35
MUTATION_PROBABILITY = 0.05
CROSSOVER_PROBABILITY = 0.6
MUTATION_RANGE = 0.04
MUTATION_DISTRIBTION = "uniform"


# region blr
# RADIUS = 4
# N_CIRCLES = 12
# POPULATION = 40
# SELECTION_PERCENTAGE = 0.35
# MUTATION_PROBABILITY = 0.05
# CROSSOVER_PROBABILITY = 0.6
# MUTATION_RANGE = 0.036
# MUTATION_DISTRIBTION = "uniform"
